
services:
  backend:  
    build: ./backend 
    
    environment:
      - PYTHONUNBUFFERED=1

  frontend: 
    build: ./frontend 
    ports:
      - "8501:8501"  

    environment:
        - STREAMLIT_API_URL=http://backend:8000     
    depends_on:
      - backend  
     